#pragma once

#include <hardware/flash.h>

#define FLASH_LAYOUT_BASE                   XIP_BASE
#define FLASH_LAYOUT_PAGE_SIZE              FLASH_PAGE_SIZE
#define FLASH_LAYOUT_SECTOR_SIZE            FLASH_SECTOR_SIZE

#define FLASH_LAYOUT_BOOTLOADER_AREA_SIZE   (64 * 1024)
#define FLASH_LAYOUT_ACTIVE_AREA_SIZE       (512 * 1024)
#define FLASH_LAYOUT_STAGING_AREA_SIZE      FLASH_LAYOUT_ACTIVE_AREA_SIZE // Staging area size = active area size
#define FLASH_LAYOUT_CONFIG_AREA_SIZE       FLASH_LAYOUT_SECTOR_SIZE // Smallest erasable region
#define FLASH_LAYOUT_TOTAL_SIZE             (2 * 1024 * 1024)

#define FLASH_LAYOUT_ACTIVE_AREA_OFFSET     FLASH_LAYOUT_BOOTLOADER_AREA_SIZE
#define FLASH_LAYOUT_STAGING_AREA_OFFSET    (FLASH_LAYOUT_ACTIVE_AREA_OFFSET + FLASH_LAYOUT_ACTIVE_AREA_SIZE)
#define FLASH_LAYOUT_CONFIG_AREA_OFFSET     (FLASH_LAYOUT_TOTAL_SIZE - FLASH_LAYOUT_CONFIG_AREA_SIZE) // Last sector

#define FLASH_LAYOUT_CONFIG_STATUS_OFFSET   0
