#pragma once

#define AUDIO_SAMPLE_SIZE sizeof(int16_t)
#define AUDIO_CHANNELS 2

#define AUDIO_SAMPLES_TO_BYTES(x) ((x) * AUDIO_SAMPLE_SIZE)
#define AUDIO_BYTES_TO_SAMPLES(x) ((x) / AUDIO_SAMPLE_SIZE)

#define AUDIO_FRAMES_TO_BYTES(x) ((x) * (AUDIO_SAMPLE_SIZE * AUDIO_CHANNELS))
#define AUDIO_BYTES_TO_FRAMES(x) ((x) / (AUDIO_SAMPLE_SIZE * AUDIO_CHANNELS))
